### ISSUE TITLE
stop job rest api not working

### ISSUE THREAD

**Issue by fenglinnorway** [statisticsnorway/rawdata-converter#9]
I stopped a job in the folloing url:
POST {{rawdata_converter}}/jobs/01EYT6YVZH6Z68QG587JPRHJN5/stop

but after checking grafana, the job seems continue running.

**Comment by kschulst** [comment]
The issue tracker for the `rawdata-converter` is concerned with core-related tasks (and questions that contribute to clarify technical concerns e.g. related to the functionality)

Please use other channels to report issues with current implementations, such as concrete running jobs. AFAIK, this is not an issue with the generic rawdata converter core. The bundled `/jobs/<jobId>/stop` endpoint seems to be working fine for other examples.
